// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GridMVC.Entities
{
    public partial class BillType
    {
        public BillType()
        {
            Bills = new HashSet<Bill>();
        }

        public int BillTypeId { get; set; }
        public string BillType1 { get; set; }

        public virtual ICollection<Bill> Bills { get; set; }
    }
}