// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GridMVC.Entities
{
    public partial class Bill
    {
        public int BillId { get; set; }
        public int BookingId { get; set; }
        public int BillTybeId { get; set; }
        public decimal BillAmount { get; set; }
        public bool? IsActive { get; set; }
        public string UserId { get; set; }

        public virtual BillType BillTybe { get; set; }
        public virtual RoomBoking Booking { get; set; }
        public virtual AspNetUser User { get; set; }
    }
}