// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GridMVC.Entities
{
    public partial class BookingStatus
    {
        public BookingStatus()
        {
            Rooms = new HashSet<Room>();
        }

        public int BookingStatusId { get; set; }
        public string BookingStatus1 { get; set; }

        public virtual ICollection<Room> Rooms { get; set; }
    }
}