// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GridMVC.Entities
{
    public partial class Room
    {
        public int RoomId { get; set; }
        public string RoomNo { get; set; }
        public byte[] RoomImg { get; set; }
        public decimal RoomPrice { get; set; }
        public int BookingStatusId { get; set; }
        public int RoomTypeId { get; set; }
        public string RoomDesc { get; set; }
        public int RoomCapicty { get; set; }
        public bool IsActive { get; set; }
        public int? BookingId { get; set; }

        public virtual RoomBoking Booking { get; set; }
        public virtual BookingStatus BookingStatus { get; set; }
        public virtual RoomType RoomType { get; set; }
        public virtual ICollection<RoomBoking> RoomBoking { get; set; }
    }
}