// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace GridMVC.Entities
{
    public partial class RoomBoking
    {
        public RoomBoking()
        {
            Bills = new HashSet<Bill>();
            Rooms = new HashSet<Room>();
        }

        public int BookingId { get; set; }
        public string GuestName { get; set; }
        public DateTime BookingFrom { get; set; }
        public DateTime BookingTo { get; set; }
        public int AssignRoomId { get; set; }

        public string RoomNum { get; set; }
        public int? AdultsNum { get; set; }
        public string GuestAddress { get; set; }
        public decimal TotalAmount { get; set; }

       

        public virtual Room Room { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}